name: notification_dispatcher
description: Inspired by Apple's NotificationCenter. Passes information around to registered observers.
version: 0.3.2
homepage: https://github.com/pongloongyeat/notification_dispatcher

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.14.4
